# Generated by Django 5.0.1 on 2024-01-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAdmin',
        ),
    ]
