# Generated by Django 5.0.1 on 2024-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_useradmin_groups_useradmin_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
    ]
